// used github copilot here to assist with creating this feature //
const products = [
  {
    name: "Biscoff Gelato Cake",
    type: "gelato",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Black forest",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Bombe Alaska Gelato Cake",
    type: "gelato",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Brunetti Classico Rocher",
    type: "gelato",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Cassata Sicliana",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Chocolate Mud Cake",
    type: "standard",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Chocolate Souffle",
    type: "standard",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Classic Black Forest",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Classic White Forest",
    type: "standard",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Con Amore",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Cookies & Cream Cheesecake",
    type: "standard",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Croquembuoche",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Crostata",
    type: "standard",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },

  {
    name: "Fleur",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Francese",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Giant Cannoli Cake",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Julio Cesere",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Lemon Mergingue Tart",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Lemon Tart",
    type: "standard",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Millefoglie",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Mixed Berry Charlotte",
    type: "standard",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Mixed Fruit Tart",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "New York cheesecake",
    type: "standard",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Nocciolato Cake",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Opera",
    type: "standard",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Pear & Cheese Crumble",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Profiterole",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Promesse D'amore Tower",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Rocher Gelato Cake",
    type: "gelato",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Royale",
    type: "standard",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Sotto Bosco",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Strawberry Cheesecake Gelato Cake",
    type: "gelato",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Strawberry Tart",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Svizzera",
    type: "standard",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Tiramisu Semifreddo",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Torta",
    type: "premium",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
  {
    name: "Torta Di Arancia",
    type: "standard",
    image: "../images/placeholder.webp",
    link: "../sites/product-page.html",
  },
];
