// used github copilot here to assist with creating this feature //
const products = [
  {
    name: "Biscoff Gelato Cake",
    type: "gelato",
    price: "$69.00",
    image: "../images/BISC-GELATO-1024X768.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Black forest",
    type: "premium",
    price: "From: $46.00",
    image: "../images/black-forest-1024x768.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Bombe Alaska Gelato Cake",
    type: "gelato",
    price: "$69.00",
    image: "../images/Bombe-alaska.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Brunetti Classico Rocher",
    type: "premium",
    price: "From: $57.00",
    image: "../images/Chocolate-Mousse.jpg",
    link: "../sites/product-page.html",
    halal: true,
    glutenFriendly: true,
    vegan: false,
  },
  {
    name: "Cassata Sicliana",
    type: "premium",
    price: "From: $57.00",
    image: "../images/Casata.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },

  {
    name: "Choc Berry Slice",
    type: "standard",
    price: "From: $62.90",
    image: "../images/Choc-Berry.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: true,
  },

  {
    name: "Chocolate Mud Cake",
    type: "standard",
    price: "From: $43.00",
    image: "../images/Mudcake.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Chocolate Souffle",
    type: "standard",
    price: "From: $54.00",
    image: "../images/Choc-Souffle.jpg",
    link: "../sites/product-page.html",
    halal: true,
    glutenFriendly: true,
    vegan: false,
  },
  {
    name: "Classic Black Forest",
    type: "premium",
    price: "From: $125.00",
    image: "../images/Classic-Black-Forest.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Classic White Forest",
    type: "standard",
    price: "From: $125.00",
    image: "../images/Classic-White-Forest.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Con Amore",
    type: "premium",
    price: "From: $46.00",
    image: "../images/Con-Amore.jpg",
    link: "../sites/product-page.html",
    halal: true,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Cookies & Cream Cheesecake",
    type: "standard",
    price: "From: $54.00",
    image: "../images/Cookies-and-cream.jpg",
    link: "../sites/product-page.html",
    halal: true,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Croquembouche",
    type: "premium",
    price: "From: $46.00",
    image: "../images/Croquembouche.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Crostata",
    type: "standard",
    price: "$69.00",
    image: "../images/Crostata.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },

  {
    name: "Fleur",
    type: "premium",
    price: "From: $57.00",
    image: "../images/fleur.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Francese",
    type: "premium",
    price: "From: $46.00",
    image: "../images/francese.jpg",
    link: "../sites/product-page.html",
    halal: true,
    glutenFriendly: true,
    vegan: false,
  },
  {
    name: "Giant Cannoli Cake",
    type: "premium",
    price: "From: $154.40",
    image: "../images/Giant-Cannoli-Cake.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Julio Cesere",
    type: "premium",
    price: "From: $43.00",
    image: "../images/Julio-Ceasar.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Lemon Mergingue Tart",
    type: "premium",
    price: "From: $57.00",
    image: "../images/Lemon-Meringue-tart.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Lemon Tart",
    type: "standard",
    price: "From: $43.00",
    image: "../images/Lemon-Tart.png",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Millefoglie",
    type: "premium",
    price: "From: $57.00",
    image: "../images/Millefoglie.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Mixed Berry Charlotte",
    type: "standard",
    price: "From: $46.00",
    image: "../images/Mixed-Berry-Charlotte.jpg",
    link: "../sites/product-page.html",
    halal: true,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Mixed Fruit Tart",
    type: "premium",
    price: "From: $100.50",
    image: "../images/Mixed-Fruit-Tart.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "New York cheesecake",
    type: "standard",
    price: "From: $46.00",
    image: "../images/New-York-Cheesecake.jpg",
    link: "../sites/product-page.html",
    halal: true,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Nocciolato Cake",
    type: "premium",
    price: "From: $46.00",
    image: "../images/Nocciolato.jpg",
    link: "../sites/product-page.html",
    halal: true,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Opera",
    type: "standard",
    price: "From: $54.00",
    image: "../images/Opera.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Pear & Cheese Crumble",
    type: "premium",
    price: "From: $100.50",
    image: "../images/Pear-Cheesecake-Crumble.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Profiterole",
    type: "premium",
    price: "From: $46.00",
    image: "../images/Profiterole.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Promesse D'amore Tower",
    type: "premium",
    price: "From: $132.30",
    image: "../images/Promesse-Tower.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Rocher Gelato Cake",
    type: "gelato",
    price: "$65.00",
    image: "../images/Rocher.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Royale",
    type: "standard",
    price: "From: $46.00",
    image: "../images/Royale.jpg",
    link: "../sites/product-page.html",
    halal: true,
    glutenFriendly: true,
    vegan: false,
  },
  {
    name: "Sotto Bosco",
    type: "premium",
    price: "From: $43.00",
    image: "../images/Sotto-Bosco.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Strawberry Cheesecake Gelato Cake",
    type: "gelato",
    price: "$65.00",
    image: "../images/Strawberry-Gelato-Cheesecake.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Strawberry Tart",
    type: "premium",
    price: "From: $54.00",
    image: "../images/Strawberry-Tart.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Svizzera",
    type: "standard",
    price: "From: $43.00",
    image: "../images/Svizzera.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Tiramisu Semifreddo",
    type: "premium",
    price: "From: $46.00",
    image: "../images/Tiramisu.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Torta",
    type: "premium",
    price: "From: $65.00",
    image: "../images/Torta.jpg",
    link: "../sites/product-page.html",
    halal: false,
    glutenFriendly: false,
    vegan: false,
  },
  {
    name: "Torta Di Arancia",
    type: "standard",
    price: "From: $54.00",
    image: "../images/Torta-Di-Arancia.jpg",
    link: "../sites/product-page.html",
    halal: true,
    glutenFriendly: true,
    vegan: false,
  },
];
